namespace SpriteKind {
    export const OcotEye = SpriteKind.create()
    export const Tentacle = SpriteKind.create()
    export const HitTentacle = SpriteKind.create()
    export const Display = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Tentacle, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    music.smallCrash.play()
    scene.cameraShake(5, 500)
    otherSprite.setKind(SpriteKind.HitTentacle)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    bullet = sprites.createProjectileFromSprite(assets.image`beam`, thePlayer, 180, 0)
    music.pewPew.play()
    pause(250)
})
function reverseVelocity (sprite: Sprite) {
    if (sprite.bottom < scene.screenHeight() + 10 && sprite.y > 60) {
        sprite.vy = 10
        sprite.ay = 0 - sprite.ay
        sprite.setFlag(SpriteFlag.AutoDestroy, true)
    } else if (sprite.top > -10 && sprite.y < 60) {
        sprite.vy = -10
        sprite.ay = 0 - sprite.ay
        sprite.setFlag(SpriteFlag.AutoDestroy, true)
    }
}
function setEyePosition () {
    octoEye.setPosition(octopus.x - 25, octopus.y - 20)
}
function makeOctoBOSS () {
    octopus = sprites.create(img`
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ....................................................................................................
        ..........................................88888888888888888.........................................
        .......................................888aaaaaaaaaaaaaaaaa888......................................
        .....................................88aaaaaaaaaaaaaaaaaaaaaaa88....................................
        ..................................888aaaaaaaaaaaaaaaaaaaaaaaaaaa888.................................
        .................................8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8................................
        ...............................88aaaaaaaccccccccccaaaaaaaaaaaaaaaaaa88..............................
        ..............................8aaaaaaaaccccccccccccaaaaaaaaaaaaaaaaaaa8.............................
        .............................8aaaaaaaaccccccccccccccaaaaaaaaaaaaaaaaaaa8............................
        ...........................88aaaaaaaacccccaaaaaacccccaaaaaaaaaaaaaaaaaaa88..........................
        ..........................8aaaaaaaaaaccccaaaaaaaaccccaaaaaaaaaaaaaaaaaaaaa8.........................
        .........................8aaaaaaaaaaacccaaaaaaaaaacccaaaaaaaaaaaaaaaaaaaaaa8........................
        .........................8aaaaaaaaaaccccaaaaaaaaaacccaaaaaaaaaaaaaaaaaaaaaa8........................
        ........................8aaaaaaaaaaaccccaaaaaaaacccccaaaaaaaaaaaaaaaaaaaaaaa8.......................
        .......................8aaaaaaaaaaaaccccccaacccccccccaaaaaaaaaaaaaaaaaaaaaaaa8......................
        ......................8aaaaaaaaaaaaaacccccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaa8.....................
        ......................8aaaaaaaaaaaaaaaccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaa8.....................
        .....................8aaaaaaaaaaaaaaaaaaccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8....................
        ....................8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8...................
        ....................8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8...................
        ....................8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8...................
        ...................8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8..................
        ...................cccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8..................
        ..................8cccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8.................
        ..................8cccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8.................
        ..................8ccccaaaaaaaaaaaaacccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8.................
        .................8accccaaaaaaaaaaaaccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8................
        .................8aacccaaaaaaaaaaaacccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8................
        .................8aacccaaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8................
        .................8aacccaaaaaaaaaaaccccaaaccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8................
        .................8aacccaaaaaaaaaaaccccaaaccccaaaaaaaaaaaaaaccccccaaaaaaaaaaaaaaaaaa8................
        .................8accccaaaaaaaaaaacccaaaaccccaaaaaaaaaaaaacccccccccaaaaaaaaaaaaaaaa8................
        .................8cccccaaaaaaaaaaccccaaaacccaaaaaaaaaaaaacccccccccccaaaaaaaaaaaaaaa8................
        .................8ccccaaaaaaaaaaaccccaaaacccaaaaaaaaaaaaaccccaaccccccaaaaaaaaaaaaaa8................
        .................8ccccaaaaaaaaaaacccaaaaccccaaaaaaaaaaaaacccaaaaaccccaaaaaaaaaaaaaa8................
        .................8cccaaaaaaaaaaaacccccacccccaaaaaaaaaaaaacccaaaaaccccaaaaaaaaaaaaaa8................
        .................8aaaaaaaaaaaaaaaccccccccccaaaaaaaaaaaaaacccaaaaacccaaaaaaaaaaaaaaa8................
        .................8aaaaaaaaaaaaaaaacccccccccaaaaaaaaaaaaaacccaaaaacccaaaaaaaaaaaaaaa8................
        .................8aaaaaaaaaaaaaaaaaacccccaaaaaaaaaaaaaaaacccaaaaacccaaaaaaaaaaaaaaa8................
        .................8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccaaaccccaaaaaaaaaaaaaaa8................
        .................8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccccacccccaaaaaaaaaaaaaaa8................
        .................8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccccccccaaaaaaaaaaaaaaaa8................
        .................8aaccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccccccaaaaaaaaaaaaaaaaa8................
        ..................ccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccaaaaaaaaaaaaaaaa8.................
        ..................ccccccccaaaaaaaaaaaaaaaaacccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8.................
        ..................cccaaccccaaaaaaaaaaaaaccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8.................
        ...................8aaaccccaaaaaaaaaaaacccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8..................
        ...................8aaaacccaaaaaaaaaaaaccccccaaaccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8..................
        ....................8aaacccaaaaaaaaaaaacccaaaaaaacccaaaaaaaaaaaaaaaaaaaaaaaaaaaa8...................
        ....................8aaccccaaaacccccaaacccaaaaaaacccaaaaaaaaaaaaaaaaaaaaaaaaaaaa8...................
        ....................8aaccccaaaccccccaaacccaaaaaaaccccaaaaaaaaaaaaaaaaaaaaaaaaaaa8...................
        .....................8accccaaccccccccaaccccaaaaccccccaaaaaaaaaaaaaaaaaaaaaaaaaa8....................
        ......................8aaaaaccccccccccaccccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaa8.....................
        ......................8aaaaaccccaaccccaaccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaa8.....................
        .......................8aaaacccaaaacccaaaccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaa8......................
        ........................8aaacccaaaacccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8.......................
        .........................8aacccaccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8........................
        .........................8aaccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8........................
        ..........................8acccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.........................
        ...........................8ccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa........................
        ............................aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.......................
        ............................aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.....................
        ...........................aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...................
        ...........aaaaa...........aaaaaa8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.................
        ...........aaaaa...........aaaaaa.8aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8aaaaaaaaaaaaaaaaaaaaa.............
        ...........aaaaa..........aaaaaaa..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..aaaaaaaaaaaaaaaaaaaaaaaa.........
        ...........aaaaa..........aaaaaa...aaaccccaaaaaaaaaaaaaaaaaaaaaaaa..aaaaaaaaaaaaaaaaaaaaaaaaaa......
        ...........aaaaaa.........aaaaaa...aaacccccaa8aaaaaaaaaaaaaaaaaaaaa..aaaaaaaaaaaaaaaaaaaaaaaaa......
        ..........3333aaaaa.......aaaaaa...aaacccccaa.aaaaaaaaaaaaaaaaaaaaa....aaaaaaaaaaaaaaaaaaaaaaa......
        ..........3333aaaaa.......aaaaa...333acccccaa.aaaaaaaaaaaaaaaaaaaaaa....aaaaaaaaaaaaaaaaaaaaaa......
        ..........3333aaaaa.......aaaaa...333acccccaa.aaaaaaaaaaaaaaaaaaaaaaa....aaaaaaaaaaaaaaaaaaaaa......
        ...........333aaaaa.......aaaaa...333accccca..aaaaaaaa.aaaaaaaaaaaaaaa.........aaaaaaaaaaa..........
        ...........333aaaaaa......aaaaa...333aacccaa..aaaaaaaa.aaaaaaaaaaaaaaaa.............................
        ............aaaaaaaa......aaaaa...333aaaaaaa..aaaaaaa333aaaaaaaaaaaaaaaa............................
        ............aaaaaaaaa.....aaaaa...aaaaaaaaaa..aaaaaaa333.aaaaaaaaaaaaaaaa...........................
        .............aaaaaaaa.....aaaaa...aaaaaaaaaa..aaaaaaa3333.aaaaaaaaaaaaaaaa..........................
        .............aaaaaaaaa....aaaaa...aaaaaaaaaa..aacccaa3333..aaaaaaaaaaaaaaaa.........................
        ..............aaaaaaaaaa..aaaaa...aaaaaaaaa...aaccccca333...aaaaaaaaaaaaaaaa........................
        ..............3333aaaaaa..aaaaa...aaaaaaaaaa...acccccca......aaaaaaaaaaaaaaa........................
        ..............33333aaaaaa.aaaaa...aaaaaaaaaa...aaccccca......aaaaaaaaaaaaaaaaaa.....................
        ..............33333aaaaaaacccaa...aaaaaaaaaa...aaaaccca.......aaaaaaaaaaaaaaaaaaaaaaa...............
        ................333aaaaaaacccaa....aaaaaaccc...aaaaccca........aaaaaaaaaaaaaaaaaaaaaaaaaa...........
        ..................aaaaaaaacccaa....aaaaaaccc...aaaaccca.........aaaaaaaaaaaaaaaaaaaaaaaaaaa.........
        ...................aaaaaaccccaaaaaaaaaaaaccca..aaaaccca..........aaaaaaaaaaaaaaaaaaaaaaaaaaa........
        .....................aaaaccccaaaaaaaaaaaaccca...aaacccc....................aaaaaaaaaaaaaaaaa........
        .........................cccaaaaaaaaaaaaacccaa..acccccc..........................aaaaaaaaaaaa.......
        ......aaaaa..............cccaaaaaaa.333aacccaa..acccccc333...........................aaaaaaaaa......
        .....aaaaaa...............aaaaaaaaa.3333acccaa..acccccc333.............................aaaaaaa......
        ....aaaaaaa...............aaaaa.....3333accccaa.aacccca333.............................aaaaaaaa.....
        ....aaaaaaa...............aaaaa......333accccaaaaaaaaaa333..............................aaaaaaa.....
        ....aaaaaaa...............aaaaa......333aaccccaaaaaaaaa..................................aaaaaa.....
        ....aaaaaa...............aaaaaa........aaaccccccaaaaaaa..................................aaaaaaa....
        ....333aa................aaaaaa.........aaacccccaaaaaaa...................................aaaaaa....
        ....333aa................aaaa333.........a333cccaaaaaaa...................................aaaaaaa...
        ....333aa...............aaaaa333.........a333aaaaaaaaa....................................aaaaaaa...
        ....333aaa..............aaaaa333..........333aaaaaaaaaa....................................aaaaaa...
        ....333aaaa............aaaaaaa.............aaaaaaaaaaaaaa..................................aaaaaa...
        ....333aaaa...........aaaaaaaa.............aaaaaaa3333aaaaa.................................aaaaaa..
        ....a333aaaa.........aaaaaaaa...............aaaaaa3333aaaaaaa...............................aaaaaa..
        .....3333cccc.......aaaaaaaaa................aaaaa3333aaaaaaaaa.............................aaaaaa..
        .....33333cccaa...aaaaaaa333.................aaaaa3333aaaaaaaaaaaa..........................aaaaaa..
        ......3333cccaaaaaaaaaaa3333.................aaaaa333aaaaaaaaaaaaaaa........................aaaaaa..
        .......333aaaaaaaaaaaaaa3333................aaaaaa333aaaaaaaaaaaaaaaaa......................aaaaaa..
        ........aaaaaaaaaaaaaaaa333................aaaaaaaa.aaaaaaaaaaaaaaaaaaa.....................aaaaaa..
        .........aaaaaaaaaaaaaaa333................aaaaaaaa...aaaaaaaaaaaaaaaaaaaaaaa...............aaaaa...
        ...........aaaaaa333aa....................aaaaaaaa......aaaaaaaaaaaaaaaaaaaaa...............aaaaa...
        .............aaa3333....................aaaacccaaa........aaaaaaaaaaaaaaaaaaa.......................
        ................3333...................aaaacccc3333...........aaaaaaaaaaaaaaa.......................
        ................333.................aaaaaaccccc3333................aaaaaaaaaa.......................
        ....................................aaaaaacccca3333.................................................
        .................................aaaaaaaaacccaa3333.................................................
        .................................aaaaaaaaacccaa.333.................................................
        .................................aaaaaaaaaaaa.......................................................
        .................................aaaaa..............................................................
        .................................aaaaa..............................................................
        ....................................................................................................
        `, SpriteKind.Enemy)
    octopus.setPosition(150, 50)
    octopus.vy = -40
    octoEye = sprites.create(img`
        ................................
        ...........fffffffffff..........
        .........ff55555555555ff........
        .......ff555555555555555ff......
        ......f5555555555555555555f.....
        .....f555555555555555555555f....
        ....f55555555555555555555555f...
        ...f5555555555555555555555555f..
        ...f5555555555555555555555555f..
        ..f555555555555555555555555555f.
        ..f555555555555555555555555555f.
        .f55555555555555555555555555555f
        .f5555555555fffffffffff55555555f
        .f5555555fffffffffffffffff55555f
        .f5555fffffffffffffffffffffff55f
        .f55ffffffffffffffffffffffffff5f
        .f55ffffffffffffffffffffffffff5f
        .f555fffffffffffffffffffffffff5f
        .f555555fffffffffffffffff555555f
        .f55555555555555555555555555555f
        .f55555555555555555555555555555f
        .f55555555555555555555555555555f
        ..f555555555555555555555555555f.
        ..f555555555555555555555555555f.
        ...f5555555555555555555555555f..
        ...f5555555555555555555555555f..
        ....f55555555555555555555555f...
        .....f555555555555555555555f....
        ......f5555555555555555555f.....
        .......ff555555555555555ff......
        .........ff55555555555ff........
        ...........fffffffffff..........
        `, SpriteKind.OcotEye)
    setEyePosition()
}
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.OcotEye, function (sprite, otherSprite) {
    eyeHP += -1
    sprite.destroy()
    if (eyeHP == 0) {
        story.printDialog("Dr. Karl has been defeated!", 90, 40, 50, 160)
        game.over(true)
    }
    otherSprite.image.replace(5, 2)
    pause(200)
    otherSprite.image.replace(2, 5)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    tentacle = sprites.create(img`
        ................
        ......aaa.......
        .....aaa........
        ...333aaa.......
        ...333aaa.......
        ...3333aa.......
        ...3333aaa......
        ...3333aaa......
        ....333aaaa.....
        ......aaaaa.....
        ......aaccc.....
        ......aacccc....
        ......aacccc....
        ......aacccc....
        ....333aaaaa....
        ....333aaaa.....
        ....333aaaa.....
        ...3333aaaa.....
        ...3333aaaa.....
        ...3333aaaa.....
        ...3333aaaa.....
        ...333aaaaa.....
        ....aaaccca.....
        ....aaaccc......
        ....accccc......
        ....accca.......
        ....accca.......
        ...aaccca.......
        ...aaccc........
        ...aaccc........
        ...aaccc........
        ...aaaaa........
        ...aaaa.........
        ...aaaa.........
        ...aaaaa........
        ....aaaaa.......
        ....aaaa33......
        ....aaaaa3......
        ....aaaaa3......
        .....aaaa3......
        .....aaaaa......
        .....aaaaa......
        .....aaaaa......
        .....aaaaa......
        .....aaaaa......
        ....aaaaa3......
        ....aaaaa3......
        ....aaaaa3......
        ....aaaaa3......
        ...3aaaaa3......
        ...3aaaaa.......
        ...3aaaaa.......
        ..33aaaaa.......
        ..aaaaaa........
        .aaaaaaa........
        .aaaaaaa........
        aaaaaaaa........
        aaaaaaa.........
        aaaaaaa.........
        accccaa.........
        cccccaa3........
        cccccaa3........
        accccaa33.......
        accccaaa3.......
        acccaaaa3.......
        aaaaaaaa3.......
        33aaaaaa3.......
        .3aaaaaa3a......
        .33aaaaaaa......
        .333aaaaaaa.....
        ..33aaaaaaa.....
        ..33aaa33aaa....
        ..33aa333aaa....
        ..aaa33333aa....
        ..aaa33333aaa...
        ..aaa33333aaa...
        .aaaa3333aaaa...
        .aaaa3333aaaa...
        .aaaa333aaaa....
        .aaaaaaaaaaa....
        .aaaaaaaaaaa....
        .3aaaaaaaaaa....
        .333aaaaaaa.....
        ..33aaaccca.....
        ..33aaccccaa....
        ..33aaccccaa....
        ..333accccaa....
        ..333accccaa....
        ..33aaacccaa....
        .33aaaaccaa.....
        .aaaaaaaaaaa....
        .aaaaaaaaaaaa...
        .aaaaaacccaaa...
        .aaaaaccccccaa..
        `, SpriteKind.Tentacle)
    tentacle.x = randint(0, scene.screenWidth() - 50)
    sprite.destroy()
    if (Math.percentChance(50)) {
        tentacle.top = scene.screenHeight()
        tentacle.ay = -200
    } else {
        tentacle.image.flipY()
        tentacle.bottom = 0
        tentacle.ay = 200
    }
})
let tentacle: Sprite = null
let octopus: Sprite = null
let bullet: Sprite = null
let eyeHP = 0
let octoEye: Sprite = null
let thePlayer: Sprite = null
story.startCutscene(function () {
    story.printDialog("Dr. Karl has taken control of the monster Octopus!", 80, 100, 50, 150)
    story.spriteSayText(thePlayer, "Dr. Karl! You need to stop this!")
    story.spriteSayText(octoEye, "I WILL DESTORY EARTH AND ALL ITS CREATURES!")
    story.printDialog("DEFEAT DR. KARL!", 80, 40, 50, 150)
})
thePlayer = sprites.create(assets.image`thePlayer`, SpriteKind.Player)
controller.moveSprite(thePlayer)
thePlayer.z = 10
effects.blizzard.startScreenEffect()
makeOctoBOSS()
info.setLife(3)
eyeHP = 50
game.onUpdate(function () {
    setEyePosition()
    for (let value of sprites.allOfKind(SpriteKind.Tentacle)) {
        reverseVelocity(value)
    }
    for (let value of sprites.allOfKind(SpriteKind.HitTentacle)) {
        reverseVelocity(value)
    }
})
game.onUpdateInterval(500, function () {
    octopus.vy = 0 - octopus.vy
})
